GET http://localhost:3000/players/

####
GET http://localhost:3000/players/2/
Content-Type: application/json

####
PUT http://localhost:3000/players/2/

####
GET http://localhost:3000/matches/18/
Content-Type: application/json

####
GET http://localhost:3000/players/7/matches/
Content-Type: application/json

####
GET http://localhost:3000/matches/2/players/
Content-Type: application/json

####
GET http://localhost:3000/players/1/playerScores/
Content-Type: application/json